language: java

jdk:
  - openjdk8

notification:
  email:
    recipients:
      - wangyu@onee.io
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.m2

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V